[book]
authors = ["George MacDonald","David MacLeod"]
language = "ie"
multilingual = false
src = "src"
title = "Li Romance de Photogen e Nycteris"
description = "Traduction de The Day Boy and Night Girl (The Romance of Photogen and Nycteris) by George MacDonald in Interlingue / Occidental."

[output.html]
theme = "src/theme"
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/occidental-lang/photogen-e-nycteris"
site-url = "/photogen-e-nycteris/"
google-analytics = "UA-151655688-1"

[output.html.fold]
enable = false

[build]
build-dir = "docs"
